### ISSUE TITLE
"Home" button does nothing when in Event Details

### ISSUE THREAD

**Issue by Pchel666** [massbay-cs/cs225-proj4#27]

**Comment by AndrewWelch33** [comment]
@Pchel666 Hey can you please go into a bit more detail of what you mean by this?

**Comment by Reztocha** [comment]
You can click on the Calendar button next to Event Details at the bottom since that's set as home.

However, it is a bit confusing to have the Home button there, but not functional.

Main.java holds the Home button along with many others. Both Main.java and MainPanel.java have JPanels that switch what's displayed according to which button within them is clicked. However, the EventDetailsPanel is not included in Main.java because it's handled in the MainPanel. So, that's why the Home doesn't work when in EventDetails.

Seems like a simple fix, but I'm still trying to figure out how.

**Comment by Reztocha** [comment]
I actually had this a bit wrong.
The Home button displays the the MainPanel. When you hit the Home button, it does nothing because the MainPanel is already being displayed.

The fix that I made was to add a method to force the MainPanel to display the Calendar when the Home button is clicked. It's kind of redundant, but it was the first thing that came to mind that didn't involve changing everything else.

**Comment by Zenexer** [comment]
@Heratcoz, please check your email and respond to Andrew if you haven't already done so.  Thanks!
